### ISSUE TITLE
Length of message error

### ISSUE THREAD

**Issue by dclardy64** [DEFENDORe/splitflap-remote#2]
Hopefully this is a question with an easy answer. I know that your install was 30 modules. I have mine at 24. I have went through every section that I can find that has 30 hardcoded or 15 hardcoded, and I have updated those to my values of 24 and 12. Even after rebuilding the web and backend, I am still getting the message below. Any ideas on where I can go to fix that? Honestly, I can read your code, but I am not extremely familiar with Node.

```
ZodError: [
  {
    "code": "too_big",
    "maximum": 24,
    "type": "string",
    "inclusive": true,
    "exact": true,
    "message": "String must contain exactly 24 character(s)",
    "path": [
      "flaps"
    ]
  }
]
    at get error (/home/dclardy/git/splitflap-remote/node_modules/zod/lib/types.js:55:31)
    at ZodObject.parseAsync (/home/dclardy/git/splitflap-remote/node_modules/zod/lib/types.js:183:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

**Comment by DEFENDORe** [comment]
Double check that line 23 in  `./web/src/routes/ManualView.vue` has been updated to 24 and try clearing your localStorage. The app saves the last entered manual message, and if it was 30 character before updating the code I can see that being the issue.
